name: Android Build
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: false

      - name: Auto Accept Android Licenses
        run: |
          yes | foo || true
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Recreate Android Framework
        run: |
          rm -rf android
          flutter create --platforms=android .
          flutter pub get

      - name: Build APK Release
        run: flutter build apk --release --no-tree-shake-icons --no-pub

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: levo-premium-app
          path: build/app/outputs/flutter-apk/app-release.apk
